# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
        
    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    - name: Download ChromeDriver
      run: |
        wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chown root:root /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    - name: Verify Google Chrome Installation
      run: |
        google-chrome --version || echo "Google Chrome is not installed."
    - name: Verify ChromeDriver Installation
      run: |
        chromedriver --version || echo "ChromeDriver is not installed."
        
    - name: Configure Chrome Options
      run: |
        echo "GOOGLE_CHROME_BIN=/usr/bin/google-chrome" >> $GITHUB_ENV
        echo "GOOGLE_CHROME_ARGS="--headless --no-sandbox --disable-dev-shm-usage --disable-gpu"" >> $GITHUB_ENV
   
    - name: Run tests
      run: mvn test
    - name: Show test results
      run: cat target/surefire-reports/*.txt

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
